
create table temp_t(
report_no int,
incident_time time,
complaint_type varchar(10),
cctv_flag varchar(5),
precinct_code int,
area_code int,
area_name varchar(20),
cctv_count int,
population_density int,
rounds_per_day int,
crime_code int,
crime_type varchar(30),
weapon_code int,
weapon_desc varchar(30),
case_status_code int,
case_status_desc varchar(10),
victim_code int,
victim_name varchar(20),
victim_sex char(1),
victim_age int,
was_victim_alone varchar(3),
is_victim_insured varchar(3),
offender_code int,
offender_name varchar(20),
offender_sex char(1),
offender_age int,
repeated_offender varchar(3),
no_of_offences int,
offender_relation varchar(3),
officer_code int,
officer_name varchar(30),
officer_sex char(1),
avg_close_days int,
week_number int,
primary key(area_code,victim_code,officer_code,report_no));

drop table temp_t;

